version: '3.4'

services:
  elasticsearch:
    #image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ES_VERSION}
    container_name: ${ES_HOST}
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${http_proxy}
        ES_VERSION: ${ES_VERSION}
        no_proxy: ${no_proxy}
    environment:
      - cluster.name=matchid-cluster
      - bootstrap.memory_lock=true
      - TAKE_FILE_OWNERSHIP=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # mem_limit: 512mM
    volumes:
     - ${ES_DATA}/node1:/usr/share/elasticsearch/data
     - ${ES_DATA}/extra:/usr/share/elasticsearch/data/extra
     #- ./elasticsearch/config:/usr/share/elasticsearch/config
     #- ${DATA_PATH}:/data
    ports:
       - "9200:9200"
    logging:
        driver: none

networks:
  default:
    external:
      name: ${DC_NETWORK}
